import Head from 'next/head';
import React, { createContext, useContext, useState } from 'react';

import styles from '@/styles/Home.module.scss';

export default function Home() {

  const ColorContext = createContext('white');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Home}>
      
    
<p>location-about-housePage-home-login</p>
{/* navbar cancellata per vercel da rifare */}
{/* <nav className={styles.navbar}>
      <ul>
        <li>
          <Link href="/housePage">House</Link>
        </li>
        <li>
          <Link href="/location">Location</Link>
        </li>
        <li>
          <Link href="/about-us">Pagina About</Link>
        </li>
        <li>
          <Link href="/login">Login</Link>
        </li>
      </ul>
    </nav> */}
      </div>
    </>
  );
}

