import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Home}>
      {/* {location.pathname === "/" && (
        <>
        <p>HomePage</p>
        <h2>Homepage</h2>
        </>
        )}
        
      <Outlet /> */}

      <p>HomePage</p>
      <h2>Homepage</h2>
      <p>
        <Link href="/about-us">Pagina About </Link>
      </p>
      <p>
        <Link href="/location">Pagina Location</Link>
      </p>
      <p>
        <Link href="/home">HomePage</Link>
      </p>
      <p>
        <Link href="/login">Login</Link>
      </p>
      <p>
        <Link href="/housePage">House</Link>
      </p>
        
    </div>
    </>
  )
}
